# Generated by Django 4.1.2 on 2022-10-28 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicsFoundation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topics', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='PhysicsHigher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topics', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='PhysicsHigher_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='mathematics_higher/')),
                ('topics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fishel.physicshigher')),
            ],
        ),
        migrations.CreateModel(
            name='PhysicsFoundation_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='mathematics_foundation/')),
                ('topics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fishel.physicsfoundation')),
            ],
        ),
    ]
